# my global config
global:
  scrape_interval: 10s  
  evaluation_interval: 10s
rule_files:
  - alert.rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - localhost:9100
  - job_name: 'tweet_app'
    static_configs:
      - targets:
        - localhost:80
